"""add Vault_item table

Revision ID: a70d1e99e918
Revises: b575ebf768c7
Create Date: 2026-10-09 16:28:09.837439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70d1e99e918'
down_revision: Union[str, Sequence[str], None] = 'b575ebf768c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('username', sa.String(length=320), nullable=True),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_notes', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_items_user_id'), 'vault_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_items_user_id'), table_name='vault_items')
    op.drop_table('vault_items')
    # ### end Alembic commands ###
